//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto.WebServiceAsoci {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioAsociacionesPortBinding", Namespace="http://servicios/")]
    public partial class ServicioAsociaciones : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarAsociacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarAsociacionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioAsociaciones() {
            this.Url = global::Proyecto.Properties.Settings.Default.Proyecto_WebServiceAsoci_ServicioAsociaciones;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarAsociacionCompletedEventHandler AgregarAsociacionCompleted;
        
        /// <remarks/>
        public event BuscarAsociacionesCompletedEventHandler BuscarAsociacionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios/", ResponseNamespace="http://servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AgregarAsociacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string asociacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idUser) {
            object[] results = this.Invoke("AgregarAsociacion", new object[] {
                        asociacion,
                        idUser});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarAsociacionAsync(string asociacion, int idUser) {
            this.AgregarAsociacionAsync(asociacion, idUser, null);
        }
        
        /// <remarks/>
        public void AgregarAsociacionAsync(string asociacion, int idUser, object userState) {
            if ((this.AgregarAsociacionOperationCompleted == null)) {
                this.AgregarAsociacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarAsociacionOperationCompleted);
            }
            this.InvokeAsync("AgregarAsociacion", new object[] {
                        asociacion,
                        idUser}, this.AgregarAsociacionOperationCompleted, userState);
        }
        
        private void OnAgregarAsociacionOperationCompleted(object arg) {
            if ((this.AgregarAsociacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarAsociacionCompleted(this, new AgregarAsociacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios/", ResponseNamespace="http://servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public asociacion[] BuscarAsociaciones([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idUser) {
            object[] results = this.Invoke("BuscarAsociaciones", new object[] {
                        idUser});
            return ((asociacion[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAsociacionesAsync(int idUser) {
            this.BuscarAsociacionesAsync(idUser, null);
        }
        
        /// <remarks/>
        public void BuscarAsociacionesAsync(int idUser, object userState) {
            if ((this.BuscarAsociacionesOperationCompleted == null)) {
                this.BuscarAsociacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAsociacionesOperationCompleted);
            }
            this.InvokeAsync("BuscarAsociaciones", new object[] {
                        idUser}, this.BuscarAsociacionesOperationCompleted, userState);
        }
        
        private void OnBuscarAsociacionesOperationCompleted(object arg) {
            if ((this.BuscarAsociacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAsociacionesCompleted(this, new BuscarAsociacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class asociacion {
        
        private int idField;
        
        private string asociacion1Field;
        
        private string adminField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("asociacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string asociacion1 {
            get {
                return this.asociacion1Field;
            }
            set {
                this.asociacion1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AgregarAsociacionCompletedEventHandler(object sender, AgregarAsociacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarAsociacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarAsociacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarAsociacionesCompletedEventHandler(object sender, BuscarAsociacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAsociacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAsociacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public asociacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((asociacion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591