//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto.WebServicePost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioPostsPortBinding", Namespace="http://servicios/")]
    public partial class ServicioPosts : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConseguirTimelineOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarPostOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgrearPostOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioPosts() {
            this.Url = global::Proyecto.Properties.Settings.Default.Proyecto_WebServicePost_ServicioPosts;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConseguirTimelineCompletedEventHandler ConseguirTimelineCompleted;
        
        /// <remarks/>
        public event BuscarPostCompletedEventHandler BuscarPostCompleted;
        
        /// <remarks/>
        public event AgrearPostCompletedEventHandler AgrearPostCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios/", ResponseNamespace="http://servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public post[] ConseguirTimeline([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idUser) {
            object[] results = this.Invoke("ConseguirTimeline", new object[] {
                        idUser});
            return ((post[])(results[0]));
        }
        
        /// <remarks/>
        public void ConseguirTimelineAsync(int idUser) {
            this.ConseguirTimelineAsync(idUser, null);
        }
        
        /// <remarks/>
        public void ConseguirTimelineAsync(int idUser, object userState) {
            if ((this.ConseguirTimelineOperationCompleted == null)) {
                this.ConseguirTimelineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConseguirTimelineOperationCompleted);
            }
            this.InvokeAsync("ConseguirTimeline", new object[] {
                        idUser}, this.ConseguirTimelineOperationCompleted, userState);
        }
        
        private void OnConseguirTimelineOperationCompleted(object arg) {
            if ((this.ConseguirTimelineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConseguirTimelineCompleted(this, new ConseguirTimelineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios/", ResponseNamespace="http://servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public post[] BuscarPost([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idUser) {
            object[] results = this.Invoke("BuscarPost", new object[] {
                        idUser});
            return ((post[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarPostAsync(int idUser) {
            this.BuscarPostAsync(idUser, null);
        }
        
        /// <remarks/>
        public void BuscarPostAsync(int idUser, object userState) {
            if ((this.BuscarPostOperationCompleted == null)) {
                this.BuscarPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPostOperationCompleted);
            }
            this.InvokeAsync("BuscarPost", new object[] {
                        idUser}, this.BuscarPostOperationCompleted, userState);
        }
        
        private void OnBuscarPostOperationCompleted(object arg) {
            if ((this.BuscarPostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPostCompleted(this, new BuscarPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios/", ResponseNamespace="http://servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AgrearPost([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string post, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int idCreador) {
            object[] results = this.Invoke("AgrearPost", new object[] {
                        post,
                        idCreador});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgrearPostAsync(string post, int idCreador) {
            this.AgrearPostAsync(post, idCreador, null);
        }
        
        /// <remarks/>
        public void AgrearPostAsync(string post, int idCreador, object userState) {
            if ((this.AgrearPostOperationCompleted == null)) {
                this.AgrearPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgrearPostOperationCompleted);
            }
            this.InvokeAsync("AgrearPost", new object[] {
                        post,
                        idCreador}, this.AgrearPostOperationCompleted, userState);
        }
        
        private void OnAgrearPostOperationCompleted(object arg) {
            if ((this.AgrearPostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgrearPostCompleted(this, new AgrearPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class post {
        
        private int idField;
        
        private string creadorField;
        
        private string post1Field;
        
        private int likesField;
        
        private int dislikesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creador {
            get {
                return this.creadorField;
            }
            set {
                this.creadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("post", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string post1 {
            get {
                return this.post1Field;
            }
            set {
                this.post1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int likes {
            get {
                return this.likesField;
            }
            set {
                this.likesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dislikes {
            get {
                return this.dislikesField;
            }
            set {
                this.dislikesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConseguirTimelineCompletedEventHandler(object sender, ConseguirTimelineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConseguirTimelineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConseguirTimelineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public post[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((post[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void BuscarPostCompletedEventHandler(object sender, BuscarPostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public post[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((post[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AgrearPostCompletedEventHandler(object sender, AgrearPostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgrearPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgrearPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591